const EventNames = {

    HTTP_REQUEST: "HTTP_REQUEST",

    USER_CREATED: "USER_CREATED",

    USER_UPDATED: "USER_UPDATED",

    USER_FOUND: "USER_FOUND",

    USER_NOT_FOUND: "USER_NOT_FOUND",

    CONVERSATION_CREATED: "CONVERSATION_CREATED",

    MESSAGE_RECEIVED: "MESSAGE_RECEIVED",

    MESSAGE_SENT: "MESSAGE_SENT",

    AI_REQUEST: "AI_REQUEST",

    AI_RESPONSE: "AI_RESPONSE",

    AI_ERROR: "AI_ERROR"

};

export default EventNames;